### ISSUE TITLE
how to make the gene family readable

### ISSUE THREAD

**Issue by ZhangDengwei** [biobakery/biobakery#21]
Hi,

my search mode is `uniref90`, and all of the genes are the uniref90 ID, like `UniRef90_Q045W4`. How can I make it readable? It seems that the utility script, humann_rename_table, also cannot handle the uniref90 but can deal with uniref50, which is a little strange.

**Comment by Wenping1975** [comment]
sorry, I don't know



---Original---

**Comment by kescobo** [comment]
Please use [the forum](https://forum.biobakery.org/c/Microbial-community-profiling/HUMAnN/) for questions about usage - in particular, you probably want to post in the HUMAnN section
