### ISSUE TITLE
MetaPhlAn3 Queries 

### ISSUE THREAD

**Issue by saras224** [biobakery/biobakery#27]
Hi 
I tried using MetaPhlAn3 for analysing my shotgun metagenome samples but I have few queries which if got answered will help me utilise the best of MetaPhlAn3.

1. My first question is that is metaphlan appropriate tool to analyse environment samples or it is basically designed for human samples only? (because my sample is environment sample)
2. I tried with few samples and got only the bacterial profiling even when I added the flag --add_viruses. The introduction of metaphlan says it can classify the sequences of eukaryotic, archeal, bacterial as well as viral sequences. So my query is that are there any parameters which I can change to get results from all the domains? if yes then where can I find those parameters with explanation?
3. Also because I am new to this field so I need to know that my samples have varying size in terms of the total reads so is it necessary that I convert them to same size( I mean normalise all the sample)?

Thank You 
Saraswati Awasthi
@fbeghini

**Comment by fbeghini** [comment]
See #19. Closing.
