### ISSUE TITLE
diamond error：Disk full？

### ISSUE THREAD

**Issue by hjdong** [biobakery/biobakery#9]
I use conda install humann2( version 2.8.1).Now  I'm have some problems with diamond(version 0.8.22) on HPC-Cluster:
```
Searching alignments... terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file /public/home/gaoxuefeng/test/p136C_3/p136C_R12_humann2_temp/tmp0UOuOq/diamond-5ed12556-174.tmp. Disk full?
terminate called recursively
terminate called recursively
terminate called recursively
......
```
The problem seems to be solved by this way:https://github.com/bbuchfink/diamond/issues/73#issue-178049961

I want to know how to modify the script parameters of the diamond.

Thanks!

**Comment by franzosa** [comment]
Please pose this question at:

https://forum.biobakery.org/c/Microbial-community-profiling/HUMAnN/5
